---
deployment:
  tasks:
    - export DEPLOYPATH=/home/Will/Desktop/Code/my-site
    - /bin/cp -R my-site $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp test.txt $DEPLOYPATH